import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { CoachingPayload } from '@/lib/schemas';
import ChatMessage from './ChatMessage';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

interface ConversationPanelProps {
  messageHistory: CoachingPayload[];
}

/**
 * ConversationPanel Component
 * 
 * Displays the interactive dialogue between the user and the AI coaching personas.
 * 
 * Design Source: Penpot file 'chessmate-panel-v1'
 * Penpot Object ID: 5cb3e3c9-c209-80cd-8006-a4207b13ad91
 * 
 * This component was auto-generated by Dr. Linus (AI Design Coach) and refactored
 * to match the high-fidelity design from Penpot.
 */
const ConversationPanel: React.FC<ConversationPanelProps> = ({ messageHistory }) => {
  return (
    <Card className="h-full flex flex-col bg-card text-card-foreground border-none p-3 gap-3">
      <CardHeader className="p-0">
        <CardTitle className="text-4xl font-bold">Conversation</CardTitle>
      </CardHeader>
      <CardContent className="flex-grow overflow-hidden p-0">
        <ScrollArea className="h-full pr-4">
          {messageHistory.length === 0 && (
            <p className="text-muted-foreground text-xl">Welcome to ChessMate! Make a move to begin your coaching session.</p>
          )}
          {messageHistory.map((msg, index) => (
            <ChatMessage key={index} message={msg} />
          ))}
        </ScrollArea>
      </CardContent>
      <div className="p-4 border-t border-border mt-auto">
        <div className="flex gap-4">
          <Input placeholder="Ask a question..." className="flex-grow text-xl h p-4" />
          <Button size="lg">Send</Button>
        </div>
      </div>
    </Card>
  );
};

export default ConversationPanel;
