"""Create initial database schema and pgai vectorizer

Revision ID: 47fccc9e92d3
Revises:
Create Date: 2025-07-28 22:10:13.860432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgai.vectorizer.configuration import (
    EmbeddingOllamaConfig,
    ChunkingRecursiveCharacterTextSplitterConfig,
    FormattingPythonTemplateConfig,
    LoadingColumnConfig,
    DestinationTableConfig
)


# revision identifiers, used by Alembic.
revision: str = '47fccc9e92d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultural_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prepared_chess_knowledge',
    sa.Column('fen', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cognitive_stage', sa.String(length=50), nullable=True),
    sa.Column('coaching_style_id', sa.Integer(), nullable=True),
    sa.Column('cultural_context_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['coaching_style_id'], ['coaching_styles.id'], ),
    sa.ForeignKeyConstraint(['cultural_context_id'], ['cultural_contexts.id'], ),
    sa.PrimaryKeyConstraint('fen')
    )
    # ### end Alembic commands ###

    op.create_vectorizer(
        source='prepared_chess_knowledge',
        name='chess_knowledge_vectorizer',
        destination=DestinationTableConfig(
            destination='prepared_chess_knowledge_embeddings'
        ),
        loading=LoadingColumnConfig(column_name='content'),
        embedding=EmbeddingOllamaConfig(
            model='nomic-embed-text',
            dimensions=768
        ),
        chunking=ChunkingRecursiveCharacterTextSplitterConfig(
            chunk_size=512,
            chunk_overlap=50
        ),
        formatting=FormattingPythonTemplateConfig(
            template='Stage: $cognitive_stage. Style: $coaching_style_id. Culture: $cultural_context_id. Language: $language. Content: $chunk'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_vectorizer(name="chess_knowledge_vectorizer", drop_all=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prepared_chess_knowledge')
    op.drop_table('cultural_contexts')
    op.drop_table('coaching_styles')
    # ### end Alembic commands ###
