# Ruff configuration for the ChessMate project
target-version = "py39"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "deps"
]

[lint]
extend-select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "ISC",# flake8-implicit-str-concat
    "N",  # pep8-naming
    "UP", # pyupgrade
    "RUF" # Ruff-specific rules
]

ignore = [
    "E501", # Line too long (handled by formatter)
    "N802", # function name should be lowercase (often conflicts with frameworks)
    "N803", # argument name should be lowercase
    "N806", # variable in function should be lowercase
    "N815", # argument name should be lowercase
    "N816", # constant name should be uppercase
]

[lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "F405"] # Allow unused imports in __init__.py

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
