# dbt_project.yml

name: 'chessmate_rag'
version: '1.0.0'
config-version: 2

profile: 'chessmate_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  chessmate_rag:
    +contract:
      enforced: true